-- MySQL Script generated by MySQL Workbench
-- Thu Dec  2 19:24:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema db_ars
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_ars` ;

-- -----------------------------------------------------
-- Schema db_ars
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_ars` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `db_ars` ;

-- -----------------------------------------------------
-- Table `m_disponibilidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `m_disponibilidad` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `m_disponibilidad` (
  `idM_disponibilidad` INT NOT NULL AUTO_INCREMENT,
  `idMedicos` INT NOT NULL,
  `idEspecialidad` INT NOT NULL,
  `HoraInico` TIME NOT NULL,
  `HoraFin` TIME NOT NULL,
  `Dia` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idM_disponibilidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `m_especialidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `m_especialidad` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `m_especialidad` (
  `idm_Especialidad` INT NOT NULL AUTO_INCREMENT,
  `NombreEspecialidad` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idm_Especialidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `medicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medicos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `medicos` (
  `idMedicos` INT NOT NULL AUTO_INCREMENT,
  `Cedula` VARCHAR(45) NOT NULL,
  `Nombres` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `HoraEntrada` DATETIME NOT NULL,
  `HoraSalida` DATETIME NOT NULL,
  `Celular` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Dirreccion` VARCHAR(100) NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  `TurnosMaximo` VARCHAR(45) NOT NULL,
  `m_disponibilidad_idM_disponibilidad` INT NOT NULL,
  `m_especialidad_idm_Especialidad` INT NOT NULL,
  PRIMARY KEY (`idMedicos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pacientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pacientes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pacientes` (
  `idPacientes` INT NOT NULL AUTO_INCREMENT,
  `Cedula` VARCHAR(45) NOT NULL,
  `NSS` VARCHAR(45) NOT NULL,
  `Nombres` VARCHAR(100) NOT NULL,
  `Apellidos` VARCHAR(100) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `Historia` VARCHAR(45) NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  `Tipificacion` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `CodigoPaciente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPacientes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `u_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u_rol` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `u_rol` (
  `idU_Rol` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idU_Rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `UsuarioNombre` VARCHAR(45) NOT NULL,
  `UsuarioClave` VARCHAR(45) NOT NULL,
  `UsuarioRol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
